pod 'Core', :git => 'git@gitlab.corp.anjuke.com:_ios/Core.git'
pod 'SDWebImage', '~>3.7'
pod 'Masonry', '~>0.6'
pod 'PSTAlertController', '1.1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
